apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: >-
      C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
      -f ../docker-horizon/docker-compose-dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: >-
          C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f ../docker-horizon/docker-compose-dev.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: api-secrets_JWT_SECRET
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: api-secrets_NODE_ENV
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: api-secrets_PORT
            - name: THROTTLE_LIMIT
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: api-secrets_THROTTLE_LIMIT
            - name: THROTTLE_WINDOW
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: api-secrets_THROTTLE_WINDOW
          image: javifdez7/horizon-api-gateway:develop
          name: horizon-api-gateway
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: '419430400'
          imagePullPolicy: Always
      restartPolicy: Always
