apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-horizon/docker-compose-dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
    - name: "6900"
      port: 6900
      targetPort: 80
      nodePort: 30000
  selector:
    io.kompose.service: api-gateway
