apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-horizon/docker-compose-dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: horizon-mongo-itineraries
  name: horizon-mongo-itineraries
spec:
  ports:
    - name: "6402"
      port: 6402
      targetPort: 27017
  selector:
    io.kompose.service: horizon-mongo-itineraries
