apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: >-
      C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
      -f ../docker-horizon/docker-compose-dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: horizon-mongo-feeds
  name: horizon-mongo-feeds
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: horizon-mongo-feeds
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: >-
          C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f ../docker-horizon/docker-compose-dev.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: horizon-mongo-feeds
    spec:
      containers:
        - image: mongo:6.0
          name: horizon-mongo-feeds
          ports:
            - containerPort: 27017
              protocol: TCP
          resources:
            limits:
              memory: '2097152e3'
          volumeMounts:
            - mountPath: /data/db
              name: horizon-mongo-feeds-volume
      restartPolicy: Always
      volumes:
        - name: horizon-mongo-feeds-volume
          persistentVolumeClaim:
            claimName: horizon-mongo-feeds-volume
