apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: horizon-mongo-notifications-volume
  name: horizon-mongo-notifications-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
