apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-horizon/docker-compose-dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: horizon-redis-meteo
  name: horizon-redis-meteo
spec:
  ports:
    - name: "6404"
      port: 6404
      targetPort: 6379
  selector:
    io.kompose.service: horizon-redis-meteo
