apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-horizon/docker-compose-dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: horizon-mongo-notifications
  name: horizon-mongo-notifications
spec:
  ports:
    - name: "6304"
      port: 6304
      targetPort: 27017
  selector:
    io.kompose.service: horizon-mongo-notifications
