apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-horizon/docker-compose-dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: itineraries
  name: itineraries
spec:
  ports:
    - name: "6401"
      port: 6401
      targetPort: 80
  selector:
    io.kompose.service: itineraries
