apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: >-
      C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
      -f ../docker-horizon/docker-compose-dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      annotations:
        kompose.cmd: >-
          C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f ../docker-horizon/docker-compose-dev.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: kafka-secrets_KAFKA_ADVERTISED_LISTENERS
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: kafka-secrets_KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: kafka-secrets_KAFKA_ZOOKEEPER_CONNECT
          image: confluentinc/cp-kafka:latest
          name: kafka
          ports:
            - containerPort: 9092
              protocol: TCP
          resources:
            limits:
              memory: '524288e3'
      restartPolicy: Always
