apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: >-
      C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
      -f ../docker-horizon/docker-compose-dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: meteo
  name: meteo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meteo
  template:
    metadata:
      annotations:
        kompose.cmd: >-
          C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f ../docker-horizon/docker-compose-dev.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: meteo
    spec:
      containers:
        - env:
            - name: ALLOWED_SERVICES
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_ALLOWED_SERVICES
            - name: BACKEND_PORT
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_BACKEND_PORT
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_GATEWAY_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_JWT_SECRET
            - name: KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_KAFKA_BROKER
            - name: KAFKA_ENABLED
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_KAFKA_ENABLED
            - name: KAFKA_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_KAFKA_SERVICE_NAME
            - name: KAFKA_TOPIC
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_KAFKA_TOPIC
            - name: LOGLEVEL
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_LOGLEVEL
            - name: MAX_REQUESTS_PER_MINUTE
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_MAX_REQUESTS_PER_MINUTE
            - name: METEO_CIRCUIT_BREAKER_FAILURE_THRESHOLD
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_METEO_CIRCUIT_BREAKER_FAILURE_THRESHOLD
            - name: METEO_CIRCUIT_BREAKER_RESET_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_METEO_CIRCUIT_BREAKER_RESET_TIMEOUT
            - name: METEO_CIRCUIT_BREAKER_SUCCESS_THRESHOLD
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_METEO_CIRCUIT_BREAKER_SUCCESS_THRESHOLD
            - name: MIN_INTERVAL_BETWEEN_REQUESTS
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_MIN_INTERVAL_BETWEEN_REQUESTS
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_NODE_ENV
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_REDIS_PORT
            - name: REDIS_TTL
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_REDIS_TTL
            - name: USE_MOCK_API
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: meteo-secrets_USE_MOCK_API
          image: javifdez7/horizon-meteo:develop
          name: horizon-meteo
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: '419430400'
          imagePullPolicy: Always
      restartPolicy: Always
