apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-horizon/docker-compose-dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: meteo
  name: meteo
spec:
  ports:
    - name: "6403"
      port: 6403
      targetPort: 80
  selector:
    io.kompose.service: meteo
