apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: >-
      C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
      -f ../docker-horizon/docker-compose-dev.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: users
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: >-
          C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f ../docker-horizon/docker-compose-dev.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: users
    spec:
      containers:
        - env:
            - name: BACKEND_PORT
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: users-secrets_BACKEND_PORT
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: users-secrets_DEBUG
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: users-secrets_GATEWAY_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: users-secrets_JWT_SECRET
            - name: LOGLEVEL
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: users-secrets_LOGLEVEL
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: users-secrets_MONGODB_URI
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: horizon-secrets
                  key: users-secrets_NODE_ENV
          image: javifdez7/horizon-users:develop
          name: horizon-users
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: '419430400'
          volumeMounts:
            - mountPath: /opt/app/logs
              name: users-claim0
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - name: users-claim0
          persistentVolumeClaim:
            claimName: users-claim0
