version: '3.8' 
services:
  ############### MICROSERVICES ############### 
  feeds:
    container_name: horizon-feeds
    image: javifdez7/horizon-feeds:develop
    environment:
      NODE_ENV: development
      BACKEND_PORT: 80
      MONGODB_URI: mongodb://horizon-mongo-feeds:27017/microservice
      DEBUG: 'true'
      LOGLEVEL: INFO
    volumes:
      - '../logs/feeds:/opt/app/logs'
    ports:
      - '6001:80'
    mem_limit: 400m
    restart: unless-stopped
  ############### DATABASES ###############
  horizon-mongo-feeds:
    container_name: horizon-mongo-feeds
    image: mongo:6.0
    volumes:
      - horizon-mongo-feeds-volume:/data/db
    ports:
      - "5001:27017"
    mem_limit: 2000m
    restart: unless-stopped

volumes:
  horizon-mongo-feeds-volume:
