version: '3.8'
services:
  ############### MICROSERVICES ############### 
  ################### FEEDS ################### 
  feeds:
    container_name: horizon-feeds
    image: javifdez7/horizon-feeds:develop
    environment:
      NODE_ENV: development
      BACKEND_PORT: 80
      MONGODB_URI: mongodb://horizon-mongo-feeds:27017/microservice
      DEBUG: 'true'
      LOGLEVEL: INFO
      KAFKA_ENABLED: 'true'
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: logs
      KAFKA_SERVICE_NAME: FEEDS
    volumes:
      - '../logs/feeds:/opt/app/logs'
    ports:
      - '6101:80'
    mem_limit: 400m
    restart: unless-stopped
    depends_on:
      - horizon-mongo-feeds
      - kafka
  #########################################
  horizon-mongo-feeds:
    container_name: horizon-mongo-feeds
    image: mongo:6.0
    volumes:
      - horizon-mongo-feeds-volume:/data/db
    ports:
      - "6102:27017"
    mem_limit: 2000m
    restart: unless-stopped
  ################### CHATS ###################
  chats:
    container_name: horizon-chats
    image: javifdez7/horizon-chats:develop
    environment:
      NODE_ENV: development
      BACKEND_PORT: 80
      MONGODB_URI: mongodb://horizon-mongo-chats:27017/microservice
      DEBUG: 'true'
      LOGLEVEL: INFO
      KAFKA_ENABLED: 'true'
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: logs
      KAFKA_SERVICE_NAME: CHATS
    volumes:
      - '../logs/chats:/opt/app/logs'
    ports:
      - '6103:80'
    mem_limit: 400m
    restart: unless-stopped
    depends_on:
      - horizon-mongo-chats
      - kafka
  #########################################
  horizon-mongo-chats:
    container_name: horizon-mongo-chats
    image: mongo:6.0
    volumes:
      - horizon-mongo-chats-volume:/data/db
    ports:
      - "6104:27017"
    mem_limit: 2000m
    restart: unless-stopped
  ################### LOGGER ###################
  logger:
    container_name: horizon-logger
    image: javifdez7/horizon-logger:develop
    environment:
      BACKEND_PORT: 6900
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: logs
      LOG_FILE_PATH: src/logs/logfile.log
    volumes:
      - '../logs/logger:/opt/app/logs'
    ports:
      - '6900:80'
    mem_limit: 400m
    restart: unless-stopped
    depends_on:
      - kafka
  ################### ZOOKEEPER ################
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4.13
    ports:
      - "2181:2181"
    mem_limit: 300m
    restart: unless-stopped
  ################### KAFKA ####################
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    mem_limit: 500m
    restart: unless-stopped
    depends_on:
      - zookeeper

  ################### ANALYTICS-REPORTS ###################
  analytics-reports:
    container_name: horizon-analytics-reports
    image: javifdez7/horizon-analytics-reports:develop
    environment:
      NODE_ENV: development
      BACKEND_PORT: 80
      MONGODB_URI: mongodb://horizon-mongo-analytics-reports:27017/microservice
      DEBUG: 'true'
      LOGLEVEL: INFO
    volumes:
      - '../logs/analytics-reports:/opt/app/logs'
    ports:
      - '6301:80'
    mem_limit: 400m
    restart: unless-stopped
  #########################################
  horizon-mongo-analytics-reports:
    container_name: horizon-mongo-analytics-reports
    image: mongo:6.0
    volumes:
      - horizon-mongo-analytics-reports-volume:/data/db
    ports:
      - "6302:27017"
    mem_limit: 2000m
    restart: unless-stopped

  ################### NOTIFICATIONS ###################
  notifications:
    container_name: horizon-notifications
    image: javifdez7/horizon-notifications:develop
    environment:
      NODE_ENV: development
      BACKEND_PORT: 80
      MONGODB_URI: mongodb://horizon-mongo-notifications:27017/microservice
      DEBUG: 'true'
      LOGLEVEL: INFO
    volumes:
      - '../logs/notifications:/opt/app/logs'
    ports:
      - '6303:80'
    mem_limit: 400m
    restart: unless-stopped
  #########################################
  horizon-mongo-notifications:
    container_name: horizon-mongo-notifications
    image: mongo:6.0
    volumes:
      - horizon-mongo-notifications-volume:/data/db
    ports:
      - "6304:27017"
    mem_limit: 2000m
    restart: unless-stopped

volumes:
  horizon-mongo-feeds-volume:
  horizon-mongo-chats-volume:
  horizon-mongo-analytics-reports-volume:
  horizon-mongo-notifications-volume:
